### ISSUE TITLE
Is hx3compat actually "deprecated" in meaning of "disapproved"?

### ISSUE THREAD

**Issue by tynrare** [HaxeFoundation/hx3compat#16]
Well, for now i'm trying to start http server on neko and only option left to test (I found ufront, tink_web, http_server) - "old" hx3compat [remoting connection](https://haxe.org/manual/std-remoting-connection.html).
So, questions:
1. Why this features was removed from language?
2. Does it "bad" to use hx3compat in terms of better practices? 
2. Is it better to directly connect hx3compat as `-lib`, or copy remote connection class code, make new package and use it as new lib?

**Comment by RealyUniqueName** [comment]
The feature is not removed from language.
We move code from standard library to "hx*compat" libraries, when we decide that code is out of scope for standard library or the code uses outdated techniques.
For example afair the remoting package was created back when there were no macros in Haxe it uses reflection and (de)serialization a lot. Such an implementation is slow and hard to maintain.
Nowadays same feature set could be implemented with macros in a better way. See [hxbit](https://github.com/HeapsIO/hxbit) as an example of similar functionality.

So, it's not bad to use hx3compat if it works for you (preferably as `-lib hx3compat`), but it's better to look for alternatives.

**Comment by tynrare** [comment]
Thanks for answer!
