### ISSUE TITLE
What's the policy for using or contributing to these modules

### ISSUE THREAD

**Issue by jonasmalacofilho** [HaxeFoundation/hx3compat#2]
1. Are there any plans to deprecate or stop maintaining these modules in the near future?
 2. Are pull requests with enhancements or new features still accepted (e.g. for `Dispatch`)?
 3. Could any of these modules be moved (again) into a separate library?

---

Essentially, while `haxe.unit` being deprecated in favor of `utest` shouldn't impact _future_ code that much, I believe `Dispatch` still serves a useful purpose, and could perhaps be handled similarly to SPOD/record-macros.

**Comment by Simn** [comment]
We don't want to do much with the code that's here. This haxelib/repository should be a temporary migration helper.

If you want to move something from it to a separate haxelib (and maintain it!), I see no reason against that. Note that regarding Dispatch, @jdonaldson is working on an alternative implementation.

**Comment by jonasmalacofilho** [comment]
Thanks, @Simn!

**Comment by jonasmalacofilho** [comment]
Concerning Dispatch, I'm following @jdonaldson 's work on [golgi](https://github.com/jdonaldson/golgi) for now...

Weren't for it, I would certainly volunteer to (officially) maintain Dispatch.

**Comment by filt3rek** [comment]
Hej,
If nobody maintains Dispatch, what will become this haxe.web package please ? SPOD is moved to record-macros, will it be something similar with Dispatch ?
Thanks for your answer !

**Comment by kevinresol** [comment]
I think if you need Dispatch (or `<insert any code in this repo here>`), you are encouraged to extract them and maintain a separate library. Or just find an existing alternative from haxelib.

Generally I will consider anything inside this repo as deprecated.
