### ISSUE TITLE
Can't compile Dispatch with haxe4 preview5

### ISSUE THREAD

**Issue by bablukid** [HaxeFoundation/hx3compat#5]
Tried to fix it but compiler gets into an infinite loop when trying to define a type for "static var GET_RULES;"
```
c:\projects\project\.haxelib\hx3compat/1,0,2/std/haxe/web/Dispatch.hx:145: characters 13-22 : Variable requires type-hint or initialization
```

```
c:\projects\project\.haxelib\hx3compat/1,0,2/std/haxe/web/Dispatch.hx:85: characters 13-23 : Unknown identifier : makeConfig
```

**Comment by bablukid** [comment]
`static var GET_RULES:Array<Array<{rule:MatchRule,opt:Bool,name:String}>> = null;`

this seems to fix the issue

**Comment by filt3rek** [comment]
Hej !

Yes, ```static var GET_RULES = null;``` is enough. Can someone fix that so we can have it clean when updating haxelib please ?

Thanks in advance,
